version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: expense-tracker-db
    environment:
      POSTGRES_DB: expense_tracker
      POSTGRES_USER: expense_user
      POSTGRES_PASSWORD: expense_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U expense_user -d expense_tracker"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Uncomment this section if you want to run the app in Docker too
  # app:
  #   build: .
  #   container_name: expense-tracker-app
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     DB_HOST: postgres
  #     DB_PORT: 5432
  #     DB_USER: expense_user
  #     DB_PASSWORD: expense_password
  #     DB_NAME: expense_tracker
  #     DB_SSLMODE: disable
  #     OPENAI_API_KEY: ${OPENAI_API_KEY}
  #     PORT: 8080
  #   depends_on:
  #     postgres:
  #       condition: service_healthy

volumes:
  postgres_data:
